name: Node.js CI
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  TEST: test
  TEST2: test2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ${{ env.TEST }}
      uses: actions/setup-node@v1
    - run: | 
        npm ci
        npm run build --if-present
    - run: npm test
      if: ${{ success() }}

